version: '3.3'
services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/
  backend:
    image: antonkrasnokutsky/coffee_bot_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
  bot:
    image: antonkrasnokutsky/coffee_bot
    restart: always
    volumes:
      - ./tg-bot-400810-9e0f62bd9a0e.json:/app/tg-bot-400810-9e0f62bd9a0e.json
    env_file:
      - .env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  db_data:
