version: '3.3'
services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/
  bot:
    image: antonkrasnokutsky/coffee_bot
    restart: always
    volumes:
      - ./tg-bot-400810-9e0f62bd9a0e.json:/app/tg-bot-400810-9e0f62bd9a0e.json
      - ./photo/:/app/photo/
    env_file:
      - .env
volumes:
  db_data:
