version: '3.3'
services:
  db:
    image: postgres:14-alpine
    env_file:
      - ../backend/.env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  db_data: