# Generated by Django 4.2.6 on 2025-11-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0016_alter_extermalworkinrepairs_external_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255, unique=True, verbose_name='Событие')),
                ('used', models.BooleanField(default=True, verbose_name='Отслеживается')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['event'],
            },
        ),
        migrations.CreateModel(
            name='EventsOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество событий')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parse_events.events', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Собитие дня',
                'verbose_name_plural': 'События дней',
                'ordering': ['-date', 'event'],
            },
        ),
        migrations.CreateModel(
            name='EventsOfPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(to='parse_events.eventsofday', verbose_name='События')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points.points', verbose_name='Точка обслуживания')),
            ],
            options={
                'verbose_name': 'Событие точки',
                'verbose_name_plural': 'События точек',
                'ordering': ['point'],
            },
        ),
    ]
