from django.urls import path

from .views import (
    AuditView,
    AuditListFilteredView,
    ExternalCompaniesChangeActivView,
    ExternalCompaniesCreateView,
    ExternalCompaniesListView,
    ExternalRepairsListFilteredView,
    ExternalRepairsView,
    ExternalRepairsSalaryView,
    ExternalTypeWorkRepairsCreateView,
    ExternalTypeWorkRepairsListVies,
    FuelCompensationListView,
    FuelCompensationCreateView,
    ServicesView,
    RepairsView,
    TypeWorkRepairsListView,
    TypeWorkRepairsCreateView,
    RepairsListFilteredView,
    ServiceListFilteredView,
)

app_name = 'points'

urlpatterns = [
    path(
        'service/',
        ServicesView.as_view()
    ),
    path(
        'repair/',
        RepairsView.as_view()
    ),
    path(
        'repairs_list/',
        RepairsListFilteredView.as_view(),
        name='repairs_list'
    ),
    path(
        'typeworkrepairs/',
        TypeWorkRepairsListView.as_view(),
        name='typeworkrepairs'
    ),
    path(
        'typeworkrepairs/add/',
        TypeWorkRepairsCreateView.as_view(),
        name='typeworkrepairs_add'
    ),
    path(
        'service_list/',
        ServiceListFilteredView.as_view(),
        name='service_list'
    ),
    path(
        'fuel_list/',
        FuelCompensationListView.as_view(),
        name='fuelcompensations'
    ),
    path(
        'fuel_create/',
        FuelCompensationCreateView.as_view(),
        name='fuelcompensations_add'
    ),
    path(
        'audit/',
        AuditView.as_view()
    ),
    path(
        'audit_list/',
        AuditListFilteredView.as_view(),
        name='audit_list'
    ),
    # Ремонт оборудования сторонних компаний
    path(
        'external/company/',
        ExternalCompaniesListView.as_view(),
        name='externalcompany',
    ),
    path(
        'external/company/create/',
        ExternalCompaniesCreateView.as_view(),
        name='externalcompany_create',
    ),
    path(
        'external/company/changeactiv/<int:company_id>/',
        ExternalCompaniesChangeActivView.as_view(),
        name='externalcompany_changeactiv',
    ),
    path(
        'external/typeworks/',
        ExternalTypeWorkRepairsListVies.as_view(),
        name='externaltypeworks_list',
    ),
    path(
        'external/typeworks/create/',
        ExternalTypeWorkRepairsCreateView.as_view(),
        name='externaltypewrok_create',
    ),
    path(
        'external/works/',
        ExternalCompaniesListView.as_view(),
        name='externalworks',
    ),
    path(
        'repairexternal/',
        ExternalRepairsView.as_view()
    ),
    path(
        'repairexternalsalary/',
        ExternalRepairsSalaryView.as_view()
    ),
    path(
        'external/repairs_list/',
        ExternalRepairsListFilteredView.as_view(),
        name='external_repairs_list'
    ),
]
