# Generated by Django 4.2.6 on 2024-02-13 08:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_serviceman_points_activ_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='serviceman',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='chocolate',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Шоколад, кг'),
        ),
        migrations.AlterField(
            model_name='services',
            name='coffee',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Кофе, кг'),
        ),
        migrations.AlterField(
            model_name='services',
            name='collection',
            field=models.PositiveIntegerField(default=0, verbose_name='Инкасация'),
        ),
        migrations.AlterField(
            model_name='services',
            name='covers',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Крышки, шт'),
        ),
        migrations.AlterField(
            model_name='services',
            name='cream',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Сливки, кг'),
        ),
        migrations.AlterField(
            model_name='services',
            name='date',
            field=models.DateTimeField(verbose_name='Дата время'),
        ),
        migrations.AlterField(
            model_name='services',
            name='glasses',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Стаканы, шт'),
        ),
        migrations.AlterField(
            model_name='services',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points.points', verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='services',
            name='raf',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Раф, кг'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points.serviceman', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='services',
            name='stirrer',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Размешиватели, шт'),
        ),
        migrations.AlterField(
            model_name='services',
            name='straws',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)], verbose_name='Трубочки, шт'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sugar',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Сахар, шт'),
        ),
        migrations.AlterField(
            model_name='services',
            name='syrup_caramel',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Сироп "Соленая карамель", шт'),
        ),
        migrations.AlterField(
            model_name='services',
            name='syrup_nut',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Сироп "Лесной орех", шт'),
        ),
        migrations.AlterField(
            model_name='services',
            name='syrup_other',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Сироп ДРУГОЙ, шт'),
        ),
    ]
