# Generated by Django 4.2.6 on 2024-03-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_repairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
