# Generated by Django 4.2.6 on 2024-04-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_points_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=255, verbose_name='Компенсация ГСМ')),
                ('price', models.PositiveIntegerField(default=0)),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeWorkRepairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typework', models.CharField(max_length=200, verbose_name='Вид работ')),
                ('price', models.PositiveIntegerField(default=0)),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
    ]
