# Generated by Django 4.2.6 on 2024-06-03 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_remove_repairs_category_remove_repairs_repair_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='services',
            name='fuelcompensation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='points.fuelcompensation', verbose_name='Компенсация ГСМ'),
        ),
        migrations.AlterField(
            model_name='fuelcompensation',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='points',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='points',
            name='tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='repairs',
            name='fuelcompensation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='points.fuelcompensation', verbose_name='Компенсация ГСМ'),
        ),
        migrations.AlterField(
            model_name='typeworkrepairs',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Тариф'),
        ),
    ]
