# Generated by Django 4.2.6 on 2024-07-05 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_alter_points_options_services_fuelcompensation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата время')),
                ('coffee', models.PositiveSmallIntegerField(default=0, verbose_name='01. Кофе зерно')),
                ('cream', models.PositiveSmallIntegerField(default=0, verbose_name='02. Заменитель сухих сливок Aristocrat "Топпинг" 1000г (8 шт. в коробке)')),
                ('chocolate', models.PositiveSmallIntegerField(default=0, verbose_name='03. Горячий шоколад Aristocrat Классический 1000г (12 шт. в коробке)')),
                ('raf', models.PositiveSmallIntegerField(default=0, verbose_name='04. Смесь сухая "Rapf-coffe" со вкусом кокоса 1000г (12 шт. в коробке)')),
                ('sugar', models.PositiveSmallIntegerField(default=0, verbose_name='05. Сахар порционный 5 г. BLACK (500 шт./кор - 2500 г.)')),
                ('glasses', models.PositiveSmallIntegerField(default=0, verbose_name='06. Стакан 350 мл. черный (50 шт/уп.)')),
                ('covers', models.PositiveSmallIntegerField(default=0, verbose_name='07. Крышка для стакана (100 шт./уп.)')),
                ('straws', models.PositiveSmallIntegerField(default=0, verbose_name='08. Трубочки коктейльные черные прямые 2*210 (1000 шт./упак)')),
                ('stirrer', models.PositiveSmallIntegerField(default=0, verbose_name='09. Размешиватель деревянный 18 см. (250 шт./упак)')),
                ('syrup_caramel', models.PositiveSmallIntegerField(default=0, verbose_name='10. Сироп "Соленая карамель" (пл. 1л.)')),
                ('syrup_nut', models.PositiveSmallIntegerField(default=0, verbose_name='11. Сироп "Лесной орех" (пл. 1л.)')),
                ('service_man', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points.serviceman', verbose_name='Исполнитель')),
            ],
        ),
    ]
