# Generated by Django 4.2.6 on 2024-07-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
