# Generated by Django 4.2.6 on 2024-08-28 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_alter_audit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='mokko',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='031. Капучино Aristocrat Mokka Toffee 1000г (12 шт. в коробке)'),
        ),
        migrations.AddField(
            model_name='services',
            name='mokko',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Мокко, кг'),
        ),
        migrations.AlterField(
            model_name='fuelcompensation',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Тариф ГСМ'),
        ),
        migrations.AlterField(
            model_name='typeworkrepairs',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Тариф на работу'),
        ),
    ]
