# Generated by Django 4.2.6 on 2025-02-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0011_audit_mokko_services_mokko_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('activ', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Внешняя компания',
                'verbose_name_plural': 'Внешние компании',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalTypeWorkRepairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typework', models.CharField(max_length=200, verbose_name='Вид работ')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Тариф на работу')),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Вид работы для внешних',
                'verbose_name_plural': 'Виды работ для внешних',
                'ordering': ['activ', 'typework'],
            },
        ),
        migrations.AddField(
            model_name='serviceman',
            name='office_engineer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExternalRepairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата время')),
                ('serial_num_coffe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серийный номер кофе')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points.externalcompanies', verbose_name='Компания')),
                ('service_man', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points.serviceman', verbose_name='Исполнитель')),
                ('typework', models.ManyToManyField(blank=True, to='points.externaltypeworkrepairs', verbose_name='Вид работ')),
            ],
            options={
                'verbose_name': 'Выполненная работа для внешних',
                'verbose_name_plural': 'Выполненные работы для внешних',
                'ordering': ['date'],
            },
        ),
    ]
