# Generated by Django 4.2.6 on 2025-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0012_externalcompanies_externaltypeworkrepairs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalrepairs',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
