# Generated by Django 4.2.6 on 2025-02-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0013_externalrepairs_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalrepairs',
            name='typework',
        ),
        migrations.CreateModel(
            name='ExtermalWorkInRepairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('external_repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typework', to='points.externalrepairs', verbose_name='Компания')),
                ('external_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points.externaltypeworkrepairs', verbose_name='Вид работы для внешних')),
            ],
            options={
                'verbose_name': 'Работа во внешнем ремонте',
                'verbose_name_plural': 'Работы во внешних ремонтах',
            },
        ),
    ]
