name: Deploy bot

on: 
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r backend/requirements.txt 
        pip install -r bot/requirements.txt 

    - name: Test with flake8 and django tests
      run: |
        python -m flake8
        python backend/manage.py test

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push coffee_bot to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./bot
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/coffee_bot:latest
      - name: Push coffee_bot_backend to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/coffee_bot_backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker compose rm -s -f backend
            sudo docker compose rm -s -f bot
            sudo docker image rm ${{ secrets.DOCKER_USERNAME }}/coffee_bot
            sudo docker image rm ${{ secrets.DOCKER_USERNAME }}/coffee_bot_backend

            rm .env
            touch .env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
            echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
            echo TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} >> .env

            echo URL_SERVICE=${{ secrets.URL_SERVICE }} >> .env
            echo URL_REPAIR=${{ secrets.URL_REPAIR }} >> .env
            echo URL_AUDIT=${{ secrets.URL_AUDIT }} >> .env
            echo URL_EXTERNAL=${{ secrets.URL_EXTERNAL }} >> .env

            echo URL_API_POINTS=${{ secrets.URL_API_POINTS }} >> .env
            echo GOOGLE_SERVICE_ACCOUNT=${{ secrets.GOOGLE_SERVICE_ACCOUNT }} >> .env
            echo CREDENTIALS_FILE=${{ secrets.CREDENTIALS_FILE }} >> .env
            echo SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }} >> .env
            echo POINTS_RANGE=${{ secrets.POINTS_RANGE }} >> .env
            echo SHEET_SERVICE=${{ secrets.SHEET_SERVICE }} >> .env
            echo SHEET_REPEAR=${{ secrets.SHEET_REPEAR }} >> .env
            echo HOST_IP=${{ secrets.HOST }} >> .env
            echo DOMAIN_NAME=${{ secrets.DOMAIN_NAME }} >> .env
            echo CHAT_ID=${{ secrets.CHAT_ID }} >> .env
            echo REPAIR_CHAT_ID=${{ secrets.REPAIR_CHAT_ID }} >> .env
            echo AUDIT_CHAT_ID=${{ secrets.AUDIT_CHAT_ID }} >> .env
            echo EXTERNAL_REPAIR_CHAT_ID=${{ secrets.EXTERNAL_REPAIR_CHAT_ID }} >> .env

            echo SERVICES=${{ secrets.SERVICES }} >> .env
            echo REPAIRS=${{ secrets.REPAIRS }} >> .env

            echo URL_API_SERVICE=${{ secrets.URL_API_SERVICE }} >> .env
            echo URL_API_REPAIR=${{ secrets.URL_API_REPAIR }} >> .env
            echo URL_API_AUDIT=${{ secrets.URL_API_AUDIT }} >> .env
            echo URL_API_EXTERNAL_REPAIR=${{ secrets.URL_API_EXTERNAL_REPAIR }} >> .env
            echo URL_API_EXTERNAL_REPAIR_SALARY=${{ secrets.URL_API_EXTERNAL_REPAIR_SALARY }} >> .env

            echo URL_API_SERVICE_MAN=${{ secrets.URL_API_SERVICE_MAN }} >> .env
            echo URL_API_AUTH=${{ secrets.URL_API_AUTH }} >> .env
            echo API_USER=${{ secrets.API_USER }} >> .env
            echo API_PASSWORD=${{ secrets.API_PASSWORD }} >> .env
            
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/coffee_bot
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/coffee_bot_backend
            sudo docker compose up -d

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен! Изменения - ${{ github.event.head_commit.message }} http://${{ secrets.DOMAIN_NAME }}/
