name: Deploy bot

on: 
  push:
    branches: [dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r backend/requirements.txt 
        pip install -r bot/requirements.txt 

    - name: Test with flake8 and django tests
      run: |
        python -m flake8
        python backend/manage.py test
